### ISSUE TITLE
I need some help!

### ISSUE THREAD

**Issue by MrFallen** [HugoJF/game-hosting-panel#9]
![image](https://user-images.githubusercontent.com/5339386/94104428-60b28980-fe7a-11ea-9500-a7fb699f6622.png)

Can you send me example for this parameters?

**Comment by MrFallen** [comment]
I found error I guess...
![image](https://user-images.githubusercontent.com/5339386/94107876-a6268500-fe81-11ea-84a7-a3292a2c1f98.png)
![image](https://user-images.githubusercontent.com/5339386/94107953-c5251700-fe81-11ea-9541-62f5d405d1d5.png)

**Comment by HugoJF** [comment]
Fixed.
